/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main_view;
import admin_panel.AdminHistoryViewForm;
import admin_panel.DashBoardPanel;
import admin_panel.MovieManagementPanel;
import admin_panel.P4_Report;
import admin_panel.SchedulePanel;
import com.formdev.flatlaf.FlatIntelliJLaf;
import javax.swing.*;
import java.awt.*;
import model.User;
        
/**
 *
 * @author OS
 */
public class Admin extends javax.swing.JFrame {
    private User user;

    public void setUser(User user) {
        this.user = user;
    }
    private MovieManagementPanel movieManagementPanel1;
    private SchedulePanel schedulePanel;
    /**
     * Creates new form Admin
     */
    public Admin() {
        initComponents();
        right_panel.removeAll();
        right_panel.add(dashBoardPanel2);
        right_panel.repaint();
        right_panel.revalidate();
        icon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        left_panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        admin_label = new javax.swing.JLabel();
        bt_dashboard = new javax.swing.JButton();
        bt_movie = new javax.swing.JButton();
        bt_schedule = new javax.swing.JButton();
        bt_report = new javax.swing.JButton();
        bt_customer = new javax.swing.JButton();
        button_dashboard5 = new javax.swing.JButton();
        lbIcon = new javax.swing.JLabel();
        right_panel = new javax.swing.JPanel();
        p4_Report1 = new admin_panel.P4_Report();
        dashBoardPanel2 = new admin_panel.DashBoardPanel();
        adminHistoryViewForm1 = new admin_panel.AdminHistoryViewForm();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        left_panel.setBackground(new java.awt.Color(0, 51, 102));

        jLabel1.setBackground(new java.awt.Color(0, 51, 102));
        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText(" Welcome");

        admin_label.setBackground(new java.awt.Color(0, 51, 102));
        admin_label.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        admin_label.setForeground(new java.awt.Color(255, 255, 255));
        admin_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        admin_label.setText("admin");

        bt_dashboard.setBackground(new java.awt.Color(0, 102, 153));
        bt_dashboard.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        bt_dashboard.setForeground(new java.awt.Color(255, 255, 255));
        bt_dashboard.setText("Dashboard");
        bt_dashboard.setBorder(null);
        bt_dashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_dashboardActionPerformed(evt);
            }
        });

        bt_movie.setBackground(new java.awt.Color(0, 51, 102));
        bt_movie.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        bt_movie.setForeground(new java.awt.Color(255, 255, 255));
        bt_movie.setText("Movie");
        bt_movie.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        bt_movie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_movieActionPerformed(evt);
            }
        });

        bt_schedule.setBackground(new java.awt.Color(0, 51, 102));
        bt_schedule.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        bt_schedule.setForeground(new java.awt.Color(255, 255, 255));
        bt_schedule.setText("Schedule");
        bt_schedule.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        bt_schedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_scheduleActionPerformed(evt);
            }
        });

        bt_report.setBackground(new java.awt.Color(0, 51, 102));
        bt_report.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        bt_report.setForeground(new java.awt.Color(255, 255, 255));
        bt_report.setText("Report");
        bt_report.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        bt_report.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_reportActionPerformed(evt);
            }
        });

        bt_customer.setBackground(new java.awt.Color(0, 51, 102));
        bt_customer.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        bt_customer.setForeground(new java.awt.Color(255, 255, 255));
        bt_customer.setText("Customer");
        bt_customer.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        bt_customer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_customerActionPerformed(evt);
            }
        });

        button_dashboard5.setBackground(new java.awt.Color(0, 51, 102));
        button_dashboard5.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        button_dashboard5.setForeground(new java.awt.Color(255, 255, 255));
        button_dashboard5.setText("log out");
        button_dashboard5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        button_dashboard5.setContentAreaFilled(false);
        button_dashboard5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_dashboard5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout left_panelLayout = new javax.swing.GroupLayout(left_panel);
        left_panel.setLayout(left_panelLayout);
        left_panelLayout.setHorizontalGroup(
            left_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bt_dashboard, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
            .addComponent(bt_movie, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bt_schedule, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bt_report, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bt_customer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(button_dashboard5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(left_panelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lbIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(left_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(left_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                    .addComponent(admin_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        left_panelLayout.setVerticalGroup(
            left_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, left_panelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lbIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(admin_label)
                .addGap(18, 18, 18)
                .addComponent(bt_dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(bt_movie, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(bt_schedule, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(bt_report, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(bt_customer, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101)
                .addComponent(button_dashboard5, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        right_panel.setBackground(new java.awt.Color(255, 255, 255));
        right_panel.setLayout(new java.awt.CardLayout());
        right_panel.add(p4_Report1, "card5");
        right_panel.add(dashBoardPanel2, "card5");
        right_panel.add(adminHistoryViewForm1, "card4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(left_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(right_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 888, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(left_panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(right_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public void icon() {
            ImageIcon userIcon = new ImageIcon("src/main/image_folder/icon.png");
            lbIcon.setIcon(userIcon);
        }
    private void bt_dashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_dashboardActionPerformed
        // TODO add your handling code here:
        showDashBoard();
        bt_dashboard.setBackground(new Color(78,139, 215));
        bt_movie.setBackground(new Color(0, 51, 102));
        bt_schedule.setBackground(new Color(0, 51, 102));
        bt_report.setBackground(new Color(0, 51, 102));
        bt_customer.setBackground(new Color(0, 51, 102));
    }//GEN-LAST:event_bt_dashboardActionPerformed
    private void showDashBoard(){
        dashBoardPanel2 = new DashBoardPanel();
         right_panel.removeAll();
        right_panel.add(dashBoardPanel2);
        right_panel.repaint();
        right_panel.revalidate();
    }
    private void bt_movieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_movieActionPerformed
        // TODO add your handling code here:
        showMovieManagement();
        bt_movie.setBackground(new Color(78,139, 215));
        bt_dashboard.setBackground(new Color(0, 51, 102));
        bt_schedule.setBackground(new Color(0, 51, 102));
        bt_report.setBackground(new Color(0, 51, 102));
        bt_customer.setBackground(new Color(0, 51, 102));
        this.repaint();
    }//GEN-LAST:event_bt_movieActionPerformed
    private void showMovieManagement(){
        movieManagementPanel1 = new MovieManagementPanel();
        right_panel.removeAll();
        right_panel.add(movieManagementPanel1);
        right_panel.repaint();
        right_panel.revalidate();
    }
    private void bt_scheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_scheduleActionPerformed
        // TODO add your handling code here:
        showScheduleManagement();
        bt_schedule.setBackground(new Color(78,139, 215));
        bt_movie.setBackground(new Color(0, 51, 102));
        bt_dashboard.setBackground(new Color(0, 51, 102));
        bt_report.setBackground(new Color(0, 51, 102));
        bt_customer.setBackground(new Color(0, 51, 102));
        
    }//GEN-LAST:event_bt_scheduleActionPerformed
    private void showScheduleManagement(){
        schedulePanel = new SchedulePanel();
        right_panel.removeAll();
        right_panel.add(schedulePanel);
        right_panel.repaint();
        right_panel.revalidate();
    }
    private void bt_reportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_reportActionPerformed
        // TODO add your handling code here:
        showReportView();
        bt_report.setBackground(new Color(78,139, 215));
        bt_movie.setBackground(new Color(0, 51, 102));
        bt_schedule.setBackground(new Color(0, 51, 102));
        bt_dashboard.setBackground(new Color(0, 51, 102));
        bt_customer.setBackground(new Color(0, 51, 102));
    }//GEN-LAST:event_bt_reportActionPerformed
    private void showReportView(){
        p4_Report1 = new P4_Report();
        right_panel.removeAll();
        right_panel.add(p4_Report1);
        right_panel.repaint();
        right_panel.revalidate();
    }
    private void bt_customerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_customerActionPerformed
        // TODO add your handling code here:
        showBookingHistory();
        bt_customer.setBackground(new Color(78,139, 215));
        bt_movie.setBackground(new Color(0, 51, 102));
        bt_schedule.setBackground(new Color(0, 51, 102));
        bt_report.setBackground(new Color(0, 51, 102));
        bt_dashboard.setBackground(new Color(0, 51, 102));
    }//GEN-LAST:event_bt_customerActionPerformed
    private void showBookingHistory(){
        adminHistoryViewForm1 = new AdminHistoryViewForm();
        right_panel.removeAll();
        right_panel.add(adminHistoryViewForm1);
        right_panel.repaint();
        right_panel.revalidate();
    }
    private void button_dashboard5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_dashboard5ActionPerformed
        // TODO add your handling code here:
        new GuestView().setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_button_dashboard5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(new FlatIntelliJLaf());
        } catch (UnsupportedLookAndFeelException e) {}

       
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private admin_panel.AdminHistoryViewForm adminHistoryViewForm1;
    private javax.swing.JLabel admin_label;
    private javax.swing.JButton bt_customer;
    private javax.swing.JButton bt_dashboard;
    private javax.swing.JButton bt_movie;
    private javax.swing.JButton bt_report;
    private javax.swing.JButton bt_schedule;
    private javax.swing.JButton button_dashboard5;
    private admin_panel.DashBoardPanel dashBoardPanel2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbIcon;
    private javax.swing.JPanel left_panel;
    private admin_panel.P4_Report p4_Report1;
    private javax.swing.JPanel right_panel;
    // End of variables declaration//GEN-END:variables
}
