/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main_view;
import admin_panel.*;
import com.formdev.flatlaf.FlatIntelliJLaf;
import customer_panel.BookingHistoryPanel;
import customer_panel.MovieDashBoardPanel;
import customer_panel.MovieInfoPanel;
import customer_panel.ScreenPanel;
import javax.swing.*;
import java.awt.*;
import model.Customer;
import model.Movie;
import model.User;
        
/**
 *
 * @author OS
 */
public class CustomerView extends javax.swing.JFrame {
    private User customer;
    private customer_panel.MovieDashBoardPanel movieDashBoardPanel1;
    private customer_panel.MovieInfoPanel movieInfoPanel1;
    private customer_panel.BookingHistoryPanel bookingHistoryPanel;
    private customer_panel.ScreenPanel screenPanel1;
    public void setCustomer(User customer) {
        this.customer = customer;
    }
    /**
     * Creates new form Admin
     */
    public CustomerView() {
        initComponents();
        
        bt_homepage.setBackground(new Color(78,139, 215));
        bt_edit_info.setBackground(new Color(0, 51, 102));
        bt_faq.setBackground(new Color(0, 51, 102));
        bt_booking_history.setBackground(new Color(0, 51, 102));
        movieDashBoardPanel1 = new MovieDashBoardPanel(this);
        showMovieDashBoard();
        icon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        right_panel = new javax.swing.JPanel();
        frequentlyAskedQuestionPanel1 = new customer_panel.FrequentlyAskedQuestionPanel();
        left_panel = new javax.swing.JPanel();
        bt_logout = new javax.swing.JButton();
        bt_homepage = new javax.swing.JButton();
        bt_faq = new javax.swing.JButton();
        bt_edit_info = new javax.swing.JButton();
        bt_booking_history = new javax.swing.JButton();
        lbIcon = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        admin_label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        right_panel.setBackground(new java.awt.Color(255, 255, 255));
        right_panel.setLayout(new java.awt.CardLayout());
        right_panel.add(frequentlyAskedQuestionPanel1, "card3");

        left_panel.setBackground(new java.awt.Color(0, 51, 102));
        left_panel.setPreferredSize(new java.awt.Dimension(200, 600));

        bt_logout.setBackground(new java.awt.Color(0, 102, 153));
        bt_logout.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        bt_logout.setForeground(new java.awt.Color(255, 255, 255));
        bt_logout.setText("Log out");
        bt_logout.setBorder(null);
        bt_logout.setContentAreaFilled(false);
        bt_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_logoutActionPerformed(evt);
            }
        });

        bt_homepage.setBackground(new java.awt.Color(0, 102, 153));
        bt_homepage.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        bt_homepage.setForeground(new java.awt.Color(255, 255, 255));
        bt_homepage.setText("Homepage");
        bt_homepage.setBorder(null);
        bt_homepage.setContentAreaFilled(false);
        bt_homepage.setOpaque(true);
        bt_homepage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_homepageActionPerformed(evt);
            }
        });

        bt_faq.setBackground(new java.awt.Color(0, 102, 153));
        bt_faq.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        bt_faq.setForeground(new java.awt.Color(255, 255, 255));
        bt_faq.setText("FAQ");
        bt_faq.setBorder(null);
        bt_faq.setContentAreaFilled(false);
        bt_faq.setOpaque(true);
        bt_faq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_faqActionPerformed(evt);
            }
        });

        bt_edit_info.setBackground(new java.awt.Color(0, 102, 153));
        bt_edit_info.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        bt_edit_info.setForeground(new java.awt.Color(255, 255, 255));
        bt_edit_info.setText("Edit Information");
        bt_edit_info.setBorder(null);
        bt_edit_info.setContentAreaFilled(false);
        bt_edit_info.setOpaque(true);
        bt_edit_info.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_edit_infoActionPerformed(evt);
            }
        });

        bt_booking_history.setBackground(new java.awt.Color(0, 102, 153));
        bt_booking_history.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        bt_booking_history.setForeground(new java.awt.Color(255, 255, 255));
        bt_booking_history.setText("BookingHistory");
        bt_booking_history.setBorder(null);
        bt_booking_history.setContentAreaFilled(false);
        bt_booking_history.setOpaque(true);
        bt_booking_history.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_booking_historyActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(0, 51, 102));
        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText(" Welcome");

        admin_label.setBackground(new java.awt.Color(0, 51, 102));
        admin_label.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        admin_label.setForeground(new java.awt.Color(255, 255, 255));
        admin_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        admin_label.setText("customer");

        javax.swing.GroupLayout left_panelLayout = new javax.swing.GroupLayout(left_panel);
        left_panel.setLayout(left_panelLayout);
        left_panelLayout.setHorizontalGroup(
            left_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bt_homepage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bt_faq, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bt_edit_info, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
            .addComponent(bt_booking_history, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(left_panelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lbIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(left_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(left_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt_logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                    .addComponent(admin_label, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        left_panelLayout.setVerticalGroup(
            left_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(left_panelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lbIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(0, 0, 0)
                .addComponent(admin_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_homepage, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(bt_faq, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(bt_edit_info, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(bt_booking_history, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bt_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(left_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(right_panel, javax.swing.GroupLayout.DEFAULT_SIZE, 994, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(right_panel, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
                    .addComponent(left_panel, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public void icon() {
        ImageIcon userIcon = new ImageIcon("src/main/image_folder/guestIcon.jpg");
        lbIcon.setIcon(userIcon);
    }
    private void bt_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_logoutActionPerformed
        // TODO add your handling code here:
        GuestView guest_view = new GuestView();
       guest_view.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_bt_logoutActionPerformed

    private void bt_homepageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_homepageActionPerformed
        // TODO add your handling code here:
        showMovieDashBoard();
        bt_homepage.setBackground(new Color(78,139, 215));
        bt_edit_info.setBackground(new Color(0, 51, 102));
        bt_faq.setBackground(new Color(0, 51, 102));
        bt_booking_history.setBackground(new Color(0, 51, 102));
    }//GEN-LAST:event_bt_homepageActionPerformed

    private void bt_faqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_faqActionPerformed
        // TODO add your handling code here:
        right_panel.removeAll();
        right_panel.add(frequentlyAskedQuestionPanel1);
        right_panel.repaint();
        right_panel.revalidate();
        bt_faq.setBackground(new Color(78,139, 215));
        bt_edit_info.setBackground(new Color(0, 51, 102));
        bt_homepage.setBackground(new Color(0, 51, 102));
        bt_booking_history.setBackground(new Color(0, 51, 102));
    }//GEN-LAST:event_bt_faqActionPerformed

    private void bt_edit_infoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_edit_infoActionPerformed
        // TODO add your handling code here:
        right_panel.removeAll();
        right_panel.add(frequentlyAskedQuestionPanel1);
        right_panel.repaint();
        right_panel.revalidate();
        bt_edit_info.setBackground(new Color(78,139, 215));
        bt_homepage.setBackground(new Color(0, 51, 102));
        bt_faq.setBackground(new Color(0, 51, 102));
        bt_booking_history.setBackground(new Color(0, 51, 102));
    }//GEN-LAST:event_bt_edit_infoActionPerformed

    private void bt_booking_historyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_booking_historyActionPerformed
        showBookingHistory();
        bt_booking_history.setBackground(new Color(78,139, 215));
        bt_edit_info.setBackground(new Color(0, 51, 102));
        bt_faq.setBackground(new Color(0, 51, 102));
        bt_homepage.setBackground(new Color(0, 51, 102));
    }//GEN-LAST:event_bt_booking_historyActionPerformed
    public void showBookingHistory(){
        // TODO add your handling code here:
        bookingHistoryPanel = new BookingHistoryPanel();
        right_panel.removeAll();
        right_panel.add(bookingHistoryPanel);
        right_panel.repaint();
        right_panel.revalidate();
    }
    public void showMovieDashBoard(){
       
        right_panel.removeAll();
        right_panel.add(movieDashBoardPanel1);
        right_panel.repaint();
        right_panel.revalidate();
    }
    
    public void showMovieInfo(Movie movie){
        movieInfoPanel1 = new MovieInfoPanel(this, movie);
        right_panel.removeAll();
        right_panel.add(movieInfoPanel1);
        right_panel.repaint();
        right_panel.revalidate();
    }
    
    public void showBookingScreen(){
        screenPanel1 = new ScreenPanel();
        screenPanel1.setUser(customer);
        right_panel.removeAll();
        right_panel.add(screenPanel1);
        right_panel.repaint();
        right_panel.revalidate();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(new FlatIntelliJLaf());
        } catch (UnsupportedLookAndFeelException e) {}

        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel admin_label;
    private javax.swing.JButton bt_booking_history;
    private javax.swing.JButton bt_edit_info;
    private javax.swing.JButton bt_faq;
    private javax.swing.JButton bt_homepage;
    private javax.swing.JButton bt_logout;
    private customer_panel.FrequentlyAskedQuestionPanel frequentlyAskedQuestionPanel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbIcon;
    private javax.swing.JPanel left_panel;
    private javax.swing.JPanel right_panel;
    // End of variables declaration//GEN-END:variables
}
