/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main_view;

import customer_panel.MovieDashBoardPanel;
import customer_panel.MovieInfoPanel;
import customer_panel.ScreenPanel;
import java.awt.Color;
import javax.swing.*;
import java.awt.*;
import model.Movie;
import model.User;
/**
 *
 * @author mac
 */
public class GuestView extends javax.swing.JFrame {
    private User customer;
    private customer_panel.MovieDashBoardPanel movieDashBoardPanel1;
    private customer_panel.MovieInfoPanel movieInfoPanel1;
    private customer_panel.BookingHistoryPanel bookingHistoryPanel;
    private customer_panel.ScreenPanel screenPanel1;
    public void setCustomer(User customer) {
        this.customer = customer;
    }
    /**
     * Creates new form GuestView
     */
    public GuestView() {
        initComponents();
        bt_homepage.setBackground(new Color(78,139, 215));
       
        bt_faq.setBackground(new Color(0, 51, 102));
        movieDashBoardPanel1 = new MovieDashBoardPanel(this);
        showMovieDashBoard();
        icon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        left_panel = new javax.swing.JPanel();
        bt_dashboard4 = new javax.swing.JButton();
        bt_homepage = new javax.swing.JButton();
        bt_dashboard6 = new javax.swing.JButton();
        bt_faq = new javax.swing.JButton();
        lbIcon = new javax.swing.JLabel();
        right_panel = new javax.swing.JPanel();
        frequentlyAskedQuestionPanel1 = new customer_panel.FrequentlyAskedQuestionPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        left_panel.setBackground(new java.awt.Color(0, 51, 102));
        left_panel.setPreferredSize(new java.awt.Dimension(200, 600));

        bt_dashboard4.setBackground(new java.awt.Color(0, 102, 153));
        bt_dashboard4.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        bt_dashboard4.setForeground(new java.awt.Color(255, 255, 255));
        bt_dashboard4.setText("Sign up");
        bt_dashboard4.setBorder(null);
        bt_dashboard4.setContentAreaFilled(false);
        bt_dashboard4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_dashboard4ActionPerformed(evt);
            }
        });

        bt_homepage.setBackground(new java.awt.Color(0, 102, 153));
        bt_homepage.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        bt_homepage.setForeground(new java.awt.Color(255, 255, 255));
        bt_homepage.setText("Homepage");
        bt_homepage.setBorder(null);
        bt_homepage.setContentAreaFilled(false);
        bt_homepage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_homepageActionPerformed(evt);
            }
        });

        bt_dashboard6.setBackground(new java.awt.Color(0, 102, 153));
        bt_dashboard6.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        bt_dashboard6.setForeground(new java.awt.Color(255, 255, 255));
        bt_dashboard6.setText("Sign in");
        bt_dashboard6.setBorder(null);
        bt_dashboard6.setContentAreaFilled(false);
        bt_dashboard6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_dashboard6ActionPerformed(evt);
            }
        });

        bt_faq.setBackground(new java.awt.Color(0, 102, 153));
        bt_faq.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        bt_faq.setForeground(new java.awt.Color(255, 255, 255));
        bt_faq.setText("FAQ");
        bt_faq.setBorder(null);
        bt_faq.setContentAreaFilled(false);
        bt_faq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_faqActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout left_panelLayout = new javax.swing.GroupLayout(left_panel);
        left_panel.setLayout(left_panelLayout);
        left_panelLayout.setHorizontalGroup(
            left_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, left_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(left_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt_homepage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                    .addComponent(bt_dashboard6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_faq, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_dashboard4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, left_panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        left_panelLayout.setVerticalGroup(
            left_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(left_panelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lbIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bt_homepage, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_faq, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 256, Short.MAX_VALUE)
                .addComponent(bt_dashboard6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_dashboard4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        right_panel.setLayout(new java.awt.CardLayout());
        right_panel.add(frequentlyAskedQuestionPanel1, "card4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(left_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(right_panel, javax.swing.GroupLayout.DEFAULT_SIZE, 992, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(right_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(left_panel, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public void showMovieDashBoard(){
        right_panel.removeAll();
        right_panel.add(movieDashBoardPanel1);
        right_panel.repaint();
        right_panel.revalidate();
    }
    public void icon() {
        ImageIcon userIcon = new ImageIcon("src/main/image_folder/guestIcon.jpg");
        lbIcon.setIcon(userIcon);
    }
    private void bt_homepageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_homepageActionPerformed
        // TODO add your handling code here:
        showMovieDashBoard();
        bt_homepage.setBackground(new Color(0,0,153));
        bt_faq.setBackground(new Color(0,51,102));

    }//GEN-LAST:event_bt_homepageActionPerformed

    private void bt_dashboard6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_dashboard6ActionPerformed
        // TODO add your handling code here:
        SignInFrame sign_in_frame = new SignInFrame();
        sign_in_frame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bt_dashboard6ActionPerformed

    private void bt_faqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_faqActionPerformed
        // TODO add your handling code here:
        bt_faq.setBackground(new Color(0,0,153));
        bt_homepage.setBackground(new Color(0,51,102));
    }//GEN-LAST:event_bt_faqActionPerformed
    public void showMovieInfo(Movie movie){
        movieInfoPanel1 = new MovieInfoPanel(this, movie);
        right_panel.removeAll();
        right_panel.add(movieInfoPanel1);
        right_panel.repaint();
        right_panel.revalidate();
    }
    
    public void showBookingScreen(){
        screenPanel1 = new ScreenPanel();
        screenPanel1.setUser(customer);
        right_panel.removeAll();
        right_panel.add(screenPanel1);
        right_panel.repaint();
        right_panel.revalidate();
    }
    private void bt_dashboard4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_dashboard4ActionPerformed
        // TODO add your handling code here:
        SignUpFrame sign_up_frame = new SignUpFrame();
        sign_up_frame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bt_dashboard4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuestView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuestView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuestView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuestView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuestView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_dashboard4;
    private javax.swing.JButton bt_dashboard6;
    private javax.swing.JButton bt_faq;
    private javax.swing.JButton bt_homepage;
    private customer_panel.FrequentlyAskedQuestionPanel frequentlyAskedQuestionPanel1;
    private javax.swing.JLabel lbIcon;
    private javax.swing.JPanel left_panel;
    private javax.swing.JPanel right_panel;
    // End of variables declaration//GEN-END:variables
}
