/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package customer_panel;

import controller.CustomerController;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Frame;
import java.awt.Graphics;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.util.ArrayList;
import java.util.function.Consumer;
import javax.imageio.ImageIO;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import main_view.CustomerView;
import main_view.GuestView;
import model.Movie;
/**
 *
 * @author mac
 */
public class MovieDashBoardPanel extends javax.swing.JPanel {
    private static CustomerController customer_controller = CustomerController.getInstance();
    private CustomerView customer_view;
    private GuestView guest_view;
    ArrayList<Movie> movies_list = customer_controller.getMovies();
    
    /**
     * Creates new form MovieDashBoardPanel
     */
    public MovieDashBoardPanel(CustomerView frame) {
        this.customer_view = frame;
        movies_list = customer_controller.getMovies();
        initComponents();
    }
    
    public MovieDashBoardPanel(GuestView frame) {
        this.guest_view = frame;
        
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tf_search = new javax.swing.JTextField();
        main_panel = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));

        tf_search.setText("Search film here...");
        tf_search.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tf_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_searchActionPerformed(evt);
            }
        });

        main_panel.setBackground(new java.awt.Color(255, 255, 255));
        main_panel.setLayout(new java.awt.GridLayout(0, 4, 10, 10));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(main_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tf_search, javax.swing.GroupLayout.DEFAULT_SIZE, 818, Short.MAX_VALUE))
                .addGap(49, 49, 49))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tf_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(main_panel, javax.swing.GroupLayout.DEFAULT_SIZE, 549, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );

        for (Movie movie : movies_list){
            JPanel moviePanel = createMoviePanel(movie);
            main_panel.add(moviePanel);

        }
        // Wrap main panel in a JScrollPane
        JScrollPane scrollPane = new JScrollPane(main_panel);
        scrollPane.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);
        scrollPane.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
        this.add(scrollPane);
        this.setVisible(true);
    }// </editor-fold>//GEN-END:initComponents
    static class ScalableImagePanel extends JPanel {
        private BufferedImage originalImage;

        public ScalableImagePanel(byte[] imageBytes) {
            try (ByteArrayInputStream is = new ByteArrayInputStream(imageBytes)) {
                this.originalImage = ImageIO.read(is);
            } catch (IOException e) {
                e.printStackTrace();
            }
        }

        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);
            if (originalImage != null) {
                // Dynamically scale the image to the current panel size
                int width = getWidth();
                int height = getHeight();
                g.drawImage(originalImage, 0, 0, width, height, this);
            }
        }
    }
    // Method to create a movie panel
    private JPanel createMoviePanel(Movie movie) {
        JPanel panel = new JPanel(new BorderLayout());
//        panel.setBorder(BorderFactory.createLineBorder(Color.black));
        panel.setBackground(Color.WHITE);
        // Custom scalable image panel
        ScalableImagePanel imagePanel = new ScalableImagePanel(movie.getImage());
        imagePanel.setPreferredSize(new Dimension(200, 300));
        
        // Movie title
        JLabel titleLabel = new JLabel(movie.getTitle(), JLabel.CENTER);
        titleLabel.setFont(new Font("Arial", Font.BOLD, 14));

        // Add components to the panel
        panel.add(imagePanel, BorderLayout.CENTER);
        panel.add(titleLabel, BorderLayout.SOUTH);
        
        panel.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                if (customer_view == null){
                    guest_view.showMovieInfo(movie);
                }else{
                    customer_view.showMovieInfo(movie);
                }
                
            }
        });
        return panel;
    }

    private void tf_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_searchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel main_panel;
    private javax.swing.JTextField tf_search;
    // End of variables declaration//GEN-END:variables
}
