/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package customer_panel;

import java.awt.BorderLayout;
import java.awt.Frame;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import main_view.CustomerView;
import main_view.GuestView;
import model.Movie;
import model.User;

/**
 *
 * @author OS
 */
public class MovieInfoPanel extends javax.swing.JPanel {
    private CustomerView customer_view;
    private GuestView user_view;
    private Movie movie;
    
    /**
     * Creates new form P2_MovieInfo
     */
    public MovieInfoPanel() {
        initComponents();
    }
    

    public MovieInfoPanel(CustomerView frame, Movie movie_){
        initComponents();
        this.customer_view = frame;
        movie = movie_;
        byte[] image_bytes = movie.getImage();
        ByteArrayInputStream input = new ByteArrayInputStream(image_bytes);
        try {
            BufferedImage buffered_image = ImageIO.read(input);
            ImageIcon imageIcon = new ImageIcon(buffered_image);
                Image image = imageIcon.getImage().getScaledInstance(360, 525, Image.SCALE_SMOOTH);
                lb_poster.setIcon(new ImageIcon(image));
        } catch (IOException ex) {
//            Logger.getLogger(MovieManagementPanel.class.getName()).log(Level.SEVERE, null, ex);
        }

        lb_title.setText(movie.getTitle());
        lb_genre.setText(movie.getGenre());
        lb_actor.setText(movie.getActor());
        lb_description.setText(movie.getDescription());
        
    }
    
    public MovieInfoPanel(GuestView frame, Movie movie_){
        initComponents();
        this.user_view = frame;
        movie = movie_;
        byte[] image_bytes = movie.getImage();
        ByteArrayInputStream input = new ByteArrayInputStream(image_bytes);
        try {
            BufferedImage buffered_image = ImageIO.read(input);
            ImageIcon imageIcon = new ImageIcon(buffered_image);
                Image image = imageIcon.getImage().getScaledInstance(360, 525, Image.SCALE_SMOOTH);
                lb_poster.setIcon(new ImageIcon(image));
        } catch (IOException ex) {
//            Logger.getLogger(MovieManagementPanel.class.getName()).log(Level.SEVERE, null, ex);
        }

        lb_title.setText(movie.getTitle());
        lb_genre.setText(movie.getGenre());
        lb_actor.setText(movie.getActor());
        lb_description.setText(movie.getDescription());
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lb_title = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lb_actor = new javax.swing.JLabel();
        lb_genre = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        bt_back = new javax.swing.JButton();
        lb_description = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        bt_book_ticket = new javax.swing.JButton();
        lb_poster = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        lb_title.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        lb_title.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lb_title.setText("La La Land");

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(24, 55, 93));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Movie Details");

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 2, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(125, 124, 123));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Actor");

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 2, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(125, 124, 123));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("Genre");

        lb_actor.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        lb_actor.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lb_actor.setText("2016");

        lb_genre.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        lb_genre.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lb_genre.setText("Drama");

        jLabel13.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(24, 55, 93));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel13.setText("Screening Details");

        jLabel15.setFont(new java.awt.Font("Helvetica Neue", 2, 16)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(125, 124, 123));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel15.setText("Time");

        jLabel17.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel17.setText("All screening time");

        bt_back.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        bt_back.setForeground(new java.awt.Color(223, 177, 96));
        bt_back.setText("back");
        bt_back.setBorder(null);
        bt_back.setContentAreaFilled(false);
        bt_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_backActionPerformed(evt);
            }
        });

        lb_description.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        lb_description.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lb_description.setText("2016");

        jLabel10.setFont(new java.awt.Font("Helvetica Neue", 2, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(125, 124, 123));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("Description");

        bt_book_ticket.setBackground(new java.awt.Color(223, 177, 96));
        bt_book_ticket.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        bt_book_ticket.setText("BOOK TICKET");
        bt_book_ticket.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bt_book_ticket.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bt_book_ticket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_book_ticketActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(bt_back, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(91, 91, 91)
                                .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel10))
                                        .addGap(45, 45, 45)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lb_actor)
                                            .addComponent(lb_genre)
                                            .addComponent(lb_description, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(lb_title, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(bt_book_ticket, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lb_title, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lb_genre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lb_actor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(lb_description, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel17))
                .addGap(56, 56, 56)
                .addComponent(bt_book_ticket, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bt_back)
                .addContainerGap())
        );

        lb_poster.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lb_poster, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(lb_poster, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bt_book_ticketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_book_ticketActionPerformed
        // TODO add your handling code here:
        if (customer_view == null){
            user_view.showBookingScreen();
            
        }else{
            customer_view.showBookingScreen();
        }
        
        
    }//GEN-LAST:event_bt_book_ticketActionPerformed

    private void bt_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_backActionPerformed
        // TODO add your handling code here:
        if (customer_view == null){
            user_view.showMovieDashBoard();
            
        }else{
            customer_view.showMovieDashBoard();
        }
       
    }//GEN-LAST:event_bt_backActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_back;
    private javax.swing.JButton bt_book_ticket;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lb_actor;
    private javax.swing.JLabel lb_description;
    private javax.swing.JLabel lb_genre;
    private javax.swing.JLabel lb_poster;
    private javax.swing.JLabel lb_title;
    // End of variables declaration//GEN-END:variables
}
